// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_TB_H_
#define FLATBUFFERS_GENERATED_COMMON_TB_H_

#include "flatbuffers/flatbuffers.h"

namespace TB {

struct Vector8Data;

struct Vector4Data;

struct Vector3Data;

struct SVector3;

struct Vector2Data;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector8Data FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;
  float x2_;
  float y2_;
  float z2_;
  float w2_;

 public:
  Vector8Data()
      : x_(0),
        y_(0),
        z_(0),
        w_(0),
        x2_(0),
        y2_(0),
        z2_(0),
        w2_(0) {
  }
  Vector8Data(float _x, float _y, float _z, float _w, float _x2, float _y2, float _z2, float _w2)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        w_(flatbuffers::EndianScalar(_w)),
        x2_(flatbuffers::EndianScalar(_x2)),
        y2_(flatbuffers::EndianScalar(_y2)),
        z2_(flatbuffers::EndianScalar(_z2)),
        w2_(flatbuffers::EndianScalar(_w2)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  void mutate_x(float _x) {
    flatbuffers::WriteScalar(&x_, _x);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  void mutate_y(float _y) {
    flatbuffers::WriteScalar(&y_, _y);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  void mutate_z(float _z) {
    flatbuffers::WriteScalar(&z_, _z);
  }
  float w() const {
    return flatbuffers::EndianScalar(w_);
  }
  void mutate_w(float _w) {
    flatbuffers::WriteScalar(&w_, _w);
  }
  float x2() const {
    return flatbuffers::EndianScalar(x2_);
  }
  void mutate_x2(float _x2) {
    flatbuffers::WriteScalar(&x2_, _x2);
  }
  float y2() const {
    return flatbuffers::EndianScalar(y2_);
  }
  void mutate_y2(float _y2) {
    flatbuffers::WriteScalar(&y2_, _y2);
  }
  float z2() const {
    return flatbuffers::EndianScalar(z2_);
  }
  void mutate_z2(float _z2) {
    flatbuffers::WriteScalar(&z2_, _z2);
  }
  float w2() const {
    return flatbuffers::EndianScalar(w2_);
  }
  void mutate_w2(float _w2) {
    flatbuffers::WriteScalar(&w2_, _w2);
  }
};
FLATBUFFERS_STRUCT_END(Vector8Data, 32);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector4Data FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vector4Data()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vector4Data(float _x, float _y, float _z, float _w)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        w_(flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  void mutate_x(float _x) {
    flatbuffers::WriteScalar(&x_, _x);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  void mutate_y(float _y) {
    flatbuffers::WriteScalar(&y_, _y);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  void mutate_z(float _z) {
    flatbuffers::WriteScalar(&z_, _z);
  }
  float w() const {
    return flatbuffers::EndianScalar(w_);
  }
  void mutate_w(float _w) {
    flatbuffers::WriteScalar(&w_, _w);
  }
};
FLATBUFFERS_STRUCT_END(Vector4Data, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3Data FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vector3Data()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3Data(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  void mutate_x(float _x) {
    flatbuffers::WriteScalar(&x_, _x);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  void mutate_y(float _y) {
    flatbuffers::WriteScalar(&y_, _y);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  void mutate_z(float _z) {
    flatbuffers::WriteScalar(&z_, _z);
  }
};
FLATBUFFERS_STRUCT_END(Vector3Data, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) SVector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  SVector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  SVector3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  void mutate_x(float _x) {
    flatbuffers::WriteScalar(&x_, _x);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  void mutate_y(float _y) {
    flatbuffers::WriteScalar(&y_, _y);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  void mutate_z(float _z) {
    flatbuffers::WriteScalar(&z_, _z);
  }
};
FLATBUFFERS_STRUCT_END(SVector3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector2Data FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vector2Data()
      : x_(0),
        y_(0) {
  }
  Vector2Data(float _x, float _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  void mutate_x(float _x) {
    flatbuffers::WriteScalar(&x_, _x);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  void mutate_y(float _y) {
    flatbuffers::WriteScalar(&y_, _y);
  }
};
FLATBUFFERS_STRUCT_END(Vector2Data, 8);

}  // namespace TB

#endif  // FLATBUFFERS_GENERATED_COMMON_TB_H_
