#pragma once

#include "HostDefine.h"

//! 20200821 Host 열거형 정의 - by thinkingpig

enum class EHOST_STATE
{
	NONE,            // 0
	ARRANGE,         // 1
	BREAK_TIME,      // 2
	END,             // 3 
	INIT,            // 3
	JUMP_BALL,       // 4
	LINE_UP,         // 5
	LOAD,            // 6
	PLAY,            // 7
	READY,           // 8
	RESULT,          // 9
	SCENE_START,     // 10
	SCORE,           // 11 
		
	CHALLENGE_INIT,
	CHALLENGE_BREAKTIME,
	CHALLENGE_READY,
	CHALLENGE_PLAY,
	CHALLENGE_END,

	TRAINING,
	TRAINING_REBOUND,
	TRAINING_JUMPSHOTBLOCK,
	TRAINING_RIMATTACKBLOCK,
	TRAINING_OFFBALLMOVE,

	TUTORIAL_BASIC,
	TUTORIAL_PASS,
	TUTORIAL_STEAL,
	TUTORIAL_DIVINGCATCH,
	TUTORIAL_JUMPSHOT,
	TUTORIAL_RIMATTACK,
	TUTORIAL_JUMPSHOTBLOCK,
	TUTORIAL_REBOUND,
	TUTORIAL_RIMATTACKBLOCK,
	TUTORIAL_BOXOUT,
	TUTORIAL_PENETRATE,
	TUTORIAL_SHOOTINGDISTURB,

	TUTORIAL_REBOUND_BEGINNER,
	TUTORIAL_BLOCK_BEGINNER,

	TUTORIA_MINIGAME_CUSTOM,
};

enum class EHOST_USER_STATE
{
	NONE,
	LOGIN,
	INIT,
	LOAD,
	SCENE_START,
	READY,
	PLAY,
	SCORE,
	SCENE_END
};

enum class EHOST_CHARACTER_STATE
{
	NONE,
	MOVE,
	STAND,
	REBOUND,
	BLOCK,
	PICK,
	SHOT,
	FAKESHOT,
	PASS,
};

enum class ESEND_MESSAGE_STATE
{
	SEND_OK,
	RECEIVE_OK,
	SEND_LIST_ZERO,
	ENCODE_FAIL,
	LAST_SEND_FAIL,
	READ_HEADER_FAIL,
	PACKET_NULL,
	NOT_FOUND_PACKET_TYPE,
	INPUT_DATA_FAIL,
};

// 클라이언트 접속 상태
enum class ECONNECT_STATE
{
	NONE,
	JOIN,		// 인게임서버에 접속해서 유저를 생성한 상태
	CONNECT,	// 인게임에 접속한 상태 
	DISCONNECT,
	WAIT,		// 재접속할 때 실제 인게임 플레이진입 전 상태, 재접속에만 상태가 있는 것 같다 
	QUIT,
}; // 재접속은 NONE -> CONNECT -> WAIT -> CONNECT 가 되는 것 같다 ( 2025- 04 -23 ) 수정이 필요할 것 같은데 

// 유저 타입
enum class EUSER_TYPE
{
	NORMAL,		// 일반 유저
	OBSERVER,	// 관전
};

// 캐릭터 타입
enum class ECHARACTER_TYPE
{
	NORMAL,		// 일반 유저 캐릭터
	AI,			// AI 캐릭터
};

// 클라가 EXIT 로 나갈 때 나가는 위치?
enum class EEXIT_TYPE
{
	NONE = 0,
	LOGIN = 1,
	LOBBY = 2,
};

enum class EMODE_TYPE
{
	NONE = 0,
	THREE_ON_THREE = 1,
	TWO_ON_TWO = 2,
	ONE_ON_ONE = 3,
	AI = 4,
	TRAINING = 5, 

	SKILL_CHALLENGE_OFF_BALL_MOVE = 6, 
	SKILL_CHALLENGE_REBOUND = 7,
	SKILL_CHALLENGE_PASS = 8,
	SKILL_CHALLENGE_JUMP_SHOT_BLOCK = 9,
	CUSTOM = 10,
	TRIO = 11,
	CONTINUOUS = 12,

	TUTORIAL_BASIC = 13,
	TUTORIAL_PASS = 14,
	TUTORIAL_STEAL = 15,
	TUTORIAL_DIVINGCATCH = 16,
	TUTORIAL_JUMPSHOT = 17,
	TUTORIAL_RIMATTACK = 18,
	TUTORIAL_JUMPSHOTBLOCK = 19,
	TUTORIAL_REBOUND = 20,
	TUTORIAL_RIMATTACKBLOCK = 21,
	TUTORIAL_BOXOUT = 22,
	TUTORIAL_PENETRATE = 23,
	TUTORIAL_SHOOTINGDISTURB = 24,

	TRAINING_REBOUND = 25,
	TRAINING_JUMPSHOTBLOCK = 26,
	TRAINING_RIMATTACKBLOCK = 27,
	TRAINING_OFFBALLMOVE = 28,

	TRIO_PVP_MIXED = 29,

	TUTORIAL_BLOCK_BEGINNER = 30,
	TUTORIAL_REBOUND_BEGINNER = 31,

	TUTORIAL_MINIGAME_CUSTOM = 32,
};

enum class ECHARACTER_ROLE
{
	ROLE_NONE = 0,
	ROLE_CENTER = 1,
	ROLE_FOWARD_POWER = 2,
	ROLE_FOWARD_SMALL = 4,
	ROLE_GUARD_POINT = 8,
	ROLE_GUARD_SHOOTING = 16,
};

enum class EBALL_STATE
{
	NONE				= 0x0000,
	ALLEYOOP			= 0x0010,
	JUMP				= 0x0020,
	LOOSE				= 0x0030,
	LOOSE_BLOCK			= 0x0031,
	LOOSE_COLLISION		= 0x0032,
	LOOSE_LAY			= 0x0033,
	LOOSE_PASS			= 0x0034,
	LOOSE_REBOUND		= 0x0035,
	LOOSE_STEAL			= 0x0036,
	PASS				= 0x0040,
	PASS_NORMAL			= 0x0041,
	PASS_BLOCK			= 0x0042,
	PASS_REBOUND		= 0x0043,
	PASS_LOOSE			= 0x0044,
	PICK				= 0x0050,
	PICK_BLOCK			= 0x0051,
	PICK_LOOSE			= 0x0052,
	PICK_PASS			= 0x0053,
	PICK_REBOUND		= 0x0054,
	PICK_STEAL			= 0x0055,
	READY				= 0x0060,
	SHOT				= 0x0070,
	SHOT_DUNK			= 0x0071,
	SHOT_JUMP			= 0x0072,
	SHOT_LAYUP			= 0x0073,
	SHOT_POST			= 0x0074,
};

enum class ELAST_ACTION_TYPE	// 기록에 필요한 것만
{
	NONE = 0,
	SHOT = 1,
	STEAL = 2,
	REBOUD = 3,
	BLOCK = 4,
};

enum class ECHARACTER_RECORD_TYPE
{
	NONE = 0,
	TRY_2POINT = 1,	// 2점슛 시도
	SUC_2POINT = 2,	// 2점슛 득점
	TRY_3POINT = 3,	// 3점슛 시도
	SUC_3POINT = 4,	// 3점슛 득점
	ASSIST = 5,		// 어시스트
	REBOUND = 6,	// 리바운드
	BLOCK = 7,		// 블럭
	STEAL = 8,		// 스틸
	LOOSE_BALL = 9,	// 루즈볼
	TURN_OVER = 10,	// 턴오버
	PASS = 11,		// 패스
	NICE_PASS = 12,	// 나이스패스
	DIVING_CATCH = 13,	// 다이빙캐치
	OVER_PASS = 14,	// 오버패스
	JUMP_SHOT_2_POINT_COUNT = 15,                          // 2점 점프샷
};

enum class EMOVEMENT_RESTRICTION
{
	NONE = 0,
	OUTSIDE_TO_INSIDE_RESTRICTION = 1,	// 공격팀이 3점 라인 안으로 못들어가게
	INSIDE_TO_OUTSIDE_RESTRICTION = 2	// 수비팀이 3점 라인 밖으로 못나가게
};

enum class EBURST_ACTION_SUBJECT
{
	NONE = 0,
	MY = 1,				// 액션 주체가 나
	OUR_TEAM = 2,		// 액션 주체가 우리팀
	OPPONENT_TEAM = 3	// 액션 주체가 상대팀
};

enum class EBURST_ON_FIRE_MODE_STEP
{
	NONE = 0,
	STEP_ONE = 1,
	STEP_TWO = 2,
};

enum class EGAME_SCORE_STATUS
{
	NONE = 0,
	LOOSING_IN_SCORE = 1,	// 지고 있는 경우
	WINNING_IN_SCORE = 2,	// 이기고 있는 경우
	TIE_IN_SCORE = 3,		// 비기고 있는 경우
};

enum class EALLEYOOP_SHOT_TYPE
{
	NONE = 0,
	LAYUP = 1,
	DUNK = 2,
};

enum class ECHARACTER_KICK_TYPE
{
	NONE = 0,
	LONG_LATENCY = 1,
	SPEED_HACK = 2,
	CHEAT_HACK = 3,
};

enum class EBAD_MANNER_TYPE
{
	NONE = 0,
	INTENTIONAL_BALL_HOG_PLAY = 1,	// 패스하지 않고 혼자 볼을 소유하는 경우
	AWAY_FROM_KEYBOARD = 2,			// 아무 조작도 하지 않는 경우
	IMPOSSIBLE_SHOOTING = 3,		// 불가능한 슈팅을 시도하는 경우
};

enum class EPLAYER_VARIABLE_TYPE
{
    NONE,

	MOVE_DEFENSE,
	MOVE_DRIBBLE, // 일단 드리블만 

	BOXOUT_RADIUS,
	BOXOUT_ANGLE,

	ENHANCED_BOXOUT_RADIUS,
	ENHANCED_BOXOUT_ANGLE,

    REBOUND_HEIGHT,
    REBOUND_HEIGHT_POWER,
    REBOUND_RADIUS,
    REBOUND_RADIUS_POWER,
    STEAL_ANIM_SPEED,
    STEAL_RADIUS,
	BLOCK_RADIUS_DUNK,
	BLOCK_RADIUS_LAYUP,
	BLOCK_RADIUS_POST_SHOT,
	BLOCK_RADIUS_FADEAWAY,
	BLOCK_RADIUS_JUMP_SHOT,
	BLOCK_HEIGHT,
	BLOCK_CONDITION_RIM_PROTECT_ANGLE,
	POPUP_CATCH_DISTANCE,
	DIVING_CATCH_PASS_DISTANCE,
	DIVING_CATCH_DISTANCE,
	PICK_UP_DISTANCE,

	BLOCK_CHASE_DOWN_PROBABILITY_DUNK,
	BLOCK_CHASE_DOWN_CATCH_PROBABILITY_DUNK,
	BLOCK_CHASE_DOWN_PROBABILITY_LAYUP,
	BLOCK_CHASE_DOWN_CATCH_PROBABILITY_LAYUP,
	BLOCK_PROBABILITY_DUNK,
	BLOCK_PROBABILITY_LAYUP,
	BLOCK_PROBABILITY_JUMP,
	BLOCK_PROBABILITY_JUMP_SHOT_RAINBOW_SHOT,
	BLOCK_PROBABILITY_POST,
	BLOCK_AND_CATCH_PROBABILITY,
	BLOCK_AND_CATCH_DUNK_PROBABILITY,
	BLOCK_POWER_BLOCK_PROBABILITY,
	SNATCH_BLOCK_BLOCK_PROBABILITY,
	DOUBLE_HANDS_UP_BLOCK_PROBABILITY,

	HOP_STEP_SHOT_RANGE,
	SPIN_MOVE_SHOT_RANGE,
	DRIVING_LAYUP_DISTANCE,
	FINGER_ROLL_DISTANCE,
	SHAKE_AND_BAKE_LAYUP_RANGE,
	EURO_STEP_LAYUP_DISTANCE_MAX,
	QUICK_LAYUP_DISTANCE_MAX,

	SHOT_FLOATER_DISTANCE_MAX,
};

enum class EACTION_VERIFY
{
	SUCCESS,
	FAIL,			// 리바운드와 같은 경우 클라가 알고있는 볼의 위치랑 서버가 알고있는 볼의 위치가 달라서 액션이 실패하는 경우가 있음
	HACK_FAIL,		// 핵? 이 감지될 경우 실패
};

enum class ECORRECTION_EARLY_TYPE
{
	NONE,
	NICE_PASS,
	BLOCK,
	STEAL,
	INTERCEPT,
	BAD_RECEIVE_LOOSE_BALL,
	PENETRATE_PIVOT,
	WIDE_OPEN_MID_RANGE_SHOT,
	WIDE_OPEN_THREE_POINT_SHOT,
};

enum class EBALL_EVENT_TYPE
{
	NONE,
	SUCCESS,
	FAIL,
};
