// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ANIMATIONINFORMATION_TB_H_
#define FLATBUFFERS_GENERATED_ANIMATIONINFORMATION_TB_H_

#include "flatbuffers/flatbuffers.h"

#include "Common_generated.h"
#include "F4Packet_generated.h"

namespace TB {

struct TBKeyframe;

struct TBAnimationCurve;
struct TBAnimationCurveBuilder;

struct TBVector3Curve;
struct TBVector3CurveBuilder;

struct TBQuaternionCurve;
struct TBQuaternionCurveBuilder;

struct TBAnimEvent;
struct TBAnimEventBuilder;

struct TBAnimationInformation;
struct TBAnimationInformationBuilder;

struct TBAnimationInformationList;
struct TBAnimationInformationListBuilder;

struct F4Balance;
struct F4BalanceBuilder;

struct F4BalanceTable;
struct F4BalanceTableBuilder;

struct F4SolutionTargetData;
struct F4SolutionTargetDataBuilder;

struct F4SolutionSaveData;
struct F4SolutionSaveDataBuilder;

struct F4SolutionSaveDataList;
struct F4SolutionSaveDataListBuilder;

enum class GAMEDATA : int8_t {
  AnimData = 1,
  BalanceData = 2,
  ShotSolutions = 3,
  MIN = AnimData,
  MAX = ShotSolutions
};

inline const GAMEDATA (&EnumValuesGAMEDATA())[3] {
  static const GAMEDATA values[] = {
    GAMEDATA::AnimData,
    GAMEDATA::BalanceData,
    GAMEDATA::ShotSolutions
  };
  return values;
}

inline const char * const *EnumNamesGAMEDATA() {
  static const char * const names[4] = {
    "AnimData",
    "BalanceData",
    "ShotSolutions",
    nullptr
  };
  return names;
}

inline const char *EnumNameGAMEDATA(GAMEDATA e) {
  if (flatbuffers::IsOutRange(e, GAMEDATA::AnimData, GAMEDATA::ShotSolutions)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(GAMEDATA::AnimData);
  return EnumNamesGAMEDATA()[index];
}

enum class WeightedMode : int8_t {
  None = 0,
  In = 1,
  Out = 2,
  Both = 3,
  MIN = None,
  MAX = Both
};

inline const WeightedMode (&EnumValuesWeightedMode())[4] {
  static const WeightedMode values[] = {
    WeightedMode::None,
    WeightedMode::In,
    WeightedMode::Out,
    WeightedMode::Both
  };
  return values;
}

inline const char * const *EnumNamesWeightedMode() {
  static const char * const names[5] = {
    "None",
    "In",
    "Out",
    "Both",
    nullptr
  };
  return names;
}

inline const char *EnumNameWeightedMode(WeightedMode e) {
  if (flatbuffers::IsOutRange(e, WeightedMode::None, WeightedMode::Both)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesWeightedMode()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) TBKeyframe FLATBUFFERS_FINAL_CLASS {
 private:
  float time_;
  float value_;
  float intangent_;
  float outtangent_;
  float inweight_;
  float outweight_;
  int8_t weighted_mode_;
  int8_t padding0__;  int16_t padding1__;

 public:
  TBKeyframe()
      : time_(0),
        value_(0),
        intangent_(0),
        outtangent_(0),
        inweight_(0),
        outweight_(0),
        weighted_mode_(0),
        padding0__(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  TBKeyframe(float _time, float _value, float _intangent, float _outtangent, float _inweight, float _outweight, TB::WeightedMode _weighted_mode)
      : time_(flatbuffers::EndianScalar(_time)),
        value_(flatbuffers::EndianScalar(_value)),
        intangent_(flatbuffers::EndianScalar(_intangent)),
        outtangent_(flatbuffers::EndianScalar(_outtangent)),
        inweight_(flatbuffers::EndianScalar(_inweight)),
        outweight_(flatbuffers::EndianScalar(_outweight)),
        weighted_mode_(flatbuffers::EndianScalar(static_cast<int8_t>(_weighted_mode))),
        padding0__(0),
        padding1__(0) {
    (void)padding0__;
    (void)padding1__;
  }
  float time() const {
    return flatbuffers::EndianScalar(time_);
  }
  float value() const {
    return flatbuffers::EndianScalar(value_);
  }
  float intangent() const {
    return flatbuffers::EndianScalar(intangent_);
  }
  float outtangent() const {
    return flatbuffers::EndianScalar(outtangent_);
  }
  float inweight() const {
    return flatbuffers::EndianScalar(inweight_);
  }
  float outweight() const {
    return flatbuffers::EndianScalar(outweight_);
  }
  TB::WeightedMode weighted_mode() const {
    return static_cast<TB::WeightedMode>(flatbuffers::EndianScalar(weighted_mode_));
  }
};
FLATBUFFERS_STRUCT_END(TBKeyframe, 28);

struct TBAnimationCurve FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TBAnimationCurveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEYS = 4
  };
  const flatbuffers::Vector<const TB::TBKeyframe *> *keys() const {
    return GetPointer<const flatbuffers::Vector<const TB::TBKeyframe *> *>(VT_KEYS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEYS) &&
           verifier.VerifyVector(keys()) &&
           verifier.EndTable();
  }
};

struct TBAnimationCurveBuilder {
  typedef TBAnimationCurve Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_keys(flatbuffers::Offset<flatbuffers::Vector<const TB::TBKeyframe *>> keys) {
    fbb_.AddOffset(TBAnimationCurve::VT_KEYS, keys);
  }
  explicit TBAnimationCurveBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TBAnimationCurve> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TBAnimationCurve>(end);
    return o;
  }
};

inline flatbuffers::Offset<TBAnimationCurve> CreateTBAnimationCurve(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<const TB::TBKeyframe *>> keys = 0) {
  TBAnimationCurveBuilder builder_(_fbb);
  builder_.add_keys(keys);
  return builder_.Finish();
}

inline flatbuffers::Offset<TBAnimationCurve> CreateTBAnimationCurveDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<TB::TBKeyframe> *keys = nullptr) {
  auto keys__ = keys ? _fbb.CreateVectorOfStructs<TB::TBKeyframe>(*keys) : 0;
  return TB::CreateTBAnimationCurve(
      _fbb,
      keys__);
}

struct TBVector3Curve FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TBVector3CurveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  const TB::TBAnimationCurve *x() const {
    return GetPointer<const TB::TBAnimationCurve *>(VT_X);
  }
  const TB::TBAnimationCurve *y() const {
    return GetPointer<const TB::TBAnimationCurve *>(VT_Y);
  }
  const TB::TBAnimationCurve *z() const {
    return GetPointer<const TB::TBAnimationCurve *>(VT_Z);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_X) &&
           verifier.VerifyTable(x()) &&
           VerifyOffset(verifier, VT_Y) &&
           verifier.VerifyTable(y()) &&
           VerifyOffset(verifier, VT_Z) &&
           verifier.VerifyTable(z()) &&
           verifier.EndTable();
  }
};

struct TBVector3CurveBuilder {
  typedef TBVector3Curve Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_x(flatbuffers::Offset<TB::TBAnimationCurve> x) {
    fbb_.AddOffset(TBVector3Curve::VT_X, x);
  }
  void add_y(flatbuffers::Offset<TB::TBAnimationCurve> y) {
    fbb_.AddOffset(TBVector3Curve::VT_Y, y);
  }
  void add_z(flatbuffers::Offset<TB::TBAnimationCurve> z) {
    fbb_.AddOffset(TBVector3Curve::VT_Z, z);
  }
  explicit TBVector3CurveBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TBVector3Curve> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TBVector3Curve>(end);
    return o;
  }
};

inline flatbuffers::Offset<TBVector3Curve> CreateTBVector3Curve(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<TB::TBAnimationCurve> x = 0,
    flatbuffers::Offset<TB::TBAnimationCurve> y = 0,
    flatbuffers::Offset<TB::TBAnimationCurve> z = 0) {
  TBVector3CurveBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct TBQuaternionCurve FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TBQuaternionCurveBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8,
    VT_W = 10
  };
  const TB::TBAnimationCurve *x() const {
    return GetPointer<const TB::TBAnimationCurve *>(VT_X);
  }
  const TB::TBAnimationCurve *y() const {
    return GetPointer<const TB::TBAnimationCurve *>(VT_Y);
  }
  const TB::TBAnimationCurve *z() const {
    return GetPointer<const TB::TBAnimationCurve *>(VT_Z);
  }
  const TB::TBAnimationCurve *w() const {
    return GetPointer<const TB::TBAnimationCurve *>(VT_W);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_X) &&
           verifier.VerifyTable(x()) &&
           VerifyOffset(verifier, VT_Y) &&
           verifier.VerifyTable(y()) &&
           VerifyOffset(verifier, VT_Z) &&
           verifier.VerifyTable(z()) &&
           VerifyOffset(verifier, VT_W) &&
           verifier.VerifyTable(w()) &&
           verifier.EndTable();
  }
};

struct TBQuaternionCurveBuilder {
  typedef TBQuaternionCurve Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_x(flatbuffers::Offset<TB::TBAnimationCurve> x) {
    fbb_.AddOffset(TBQuaternionCurve::VT_X, x);
  }
  void add_y(flatbuffers::Offset<TB::TBAnimationCurve> y) {
    fbb_.AddOffset(TBQuaternionCurve::VT_Y, y);
  }
  void add_z(flatbuffers::Offset<TB::TBAnimationCurve> z) {
    fbb_.AddOffset(TBQuaternionCurve::VT_Z, z);
  }
  void add_w(flatbuffers::Offset<TB::TBAnimationCurve> w) {
    fbb_.AddOffset(TBQuaternionCurve::VT_W, w);
  }
  explicit TBQuaternionCurveBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TBQuaternionCurve> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TBQuaternionCurve>(end);
    return o;
  }
};

inline flatbuffers::Offset<TBQuaternionCurve> CreateTBQuaternionCurve(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<TB::TBAnimationCurve> x = 0,
    flatbuffers::Offset<TB::TBAnimationCurve> y = 0,
    flatbuffers::Offset<TB::TBAnimationCurve> z = 0,
    flatbuffers::Offset<TB::TBAnimationCurve> w = 0) {
  TBQuaternionCurveBuilder builder_(_fbb);
  builder_.add_w(w);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct TBAnimEvent FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TBAnimEventBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_KEY = 6,
    VT_TIME = 8
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const flatbuffers::String *key() const {
    return GetPointer<const flatbuffers::String *>(VT_KEY);
  }
  float time() const {
    return GetField<float>(VT_TIME, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<float>(verifier, VT_TIME) &&
           verifier.EndTable();
  }
};

struct TBAnimEventBuilder {
  typedef TBAnimEvent Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(TBAnimEvent::VT_NAME, name);
  }
  void add_key(flatbuffers::Offset<flatbuffers::String> key) {
    fbb_.AddOffset(TBAnimEvent::VT_KEY, key);
  }
  void add_time(float time) {
    fbb_.AddElement<float>(TBAnimEvent::VT_TIME, time, 0.0f);
  }
  explicit TBAnimEventBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TBAnimEvent> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TBAnimEvent>(end);
    return o;
  }
};

inline flatbuffers::Offset<TBAnimEvent> CreateTBAnimEvent(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<flatbuffers::String> key = 0,
    float time = 0.0f) {
  TBAnimEventBuilder builder_(_fbb);
  builder_.add_time(time);
  builder_.add_key(key);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<TBAnimEvent> CreateTBAnimEventDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *key = nullptr,
    float time = 0.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return TB::CreateTBAnimEvent(
      _fbb,
      name__,
      key__,
      time);
}

struct TBAnimationInformation FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TBAnimationInformationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_CURVEPOSITIONDUMMY001 = 6,
    VT_CURVEROTATIONDUMMY001 = 8,
    VT_CURVEPOSITIONBALL = 10,
    VT_CURVEROTATIONBALL = 12,
    VT_CURVEPOSITIONBALLPOINTFINGERR = 14,
    VT_CURVEPOSITIONBALLPOINTFINGERL = 16,
    VT_CURVEPOSITIONBALLPOINTR = 18,
    VT_CURVEPOSITIONBALLPOINTL = 20,
    VT_CURVEROTATIONBALLPOINTR = 22,
    VT_CURVEROTATIONBALLPOINTL = 24,
    VT_EVENTLIST = 26,
    VT_LENGTH = 28
  };
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  const TB::TBVector3Curve *curvepositiondummy001() const {
    return GetPointer<const TB::TBVector3Curve *>(VT_CURVEPOSITIONDUMMY001);
  }
  const TB::TBQuaternionCurve *curverotationdummy001() const {
    return GetPointer<const TB::TBQuaternionCurve *>(VT_CURVEROTATIONDUMMY001);
  }
  const TB::TBVector3Curve *curvepositionball() const {
    return GetPointer<const TB::TBVector3Curve *>(VT_CURVEPOSITIONBALL);
  }
  const TB::TBQuaternionCurve *curverotationball() const {
    return GetPointer<const TB::TBQuaternionCurve *>(VT_CURVEROTATIONBALL);
  }
  const TB::TBVector3Curve *curvepositionballpointfingerr() const {
    return GetPointer<const TB::TBVector3Curve *>(VT_CURVEPOSITIONBALLPOINTFINGERR);
  }
  const TB::TBVector3Curve *curvepositionballpointfingerl() const {
    return GetPointer<const TB::TBVector3Curve *>(VT_CURVEPOSITIONBALLPOINTFINGERL);
  }
  const TB::TBVector3Curve *curvepositionballpointr() const {
    return GetPointer<const TB::TBVector3Curve *>(VT_CURVEPOSITIONBALLPOINTR);
  }
  const TB::TBVector3Curve *curvepositionballpointl() const {
    return GetPointer<const TB::TBVector3Curve *>(VT_CURVEPOSITIONBALLPOINTL);
  }
  const TB::TBQuaternionCurve *curverotationballpointr() const {
    return GetPointer<const TB::TBQuaternionCurve *>(VT_CURVEROTATIONBALLPOINTR);
  }
  const TB::TBQuaternionCurve *curverotationballpointl() const {
    return GetPointer<const TB::TBQuaternionCurve *>(VT_CURVEROTATIONBALLPOINTL);
  }
  const flatbuffers::Vector<flatbuffers::Offset<TB::TBAnimEvent>> *eventlist() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<TB::TBAnimEvent>> *>(VT_EVENTLIST);
  }
  float length() const {
    return GetField<float>(VT_LENGTH, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_CURVEPOSITIONDUMMY001) &&
           verifier.VerifyTable(curvepositiondummy001()) &&
           VerifyOffset(verifier, VT_CURVEROTATIONDUMMY001) &&
           verifier.VerifyTable(curverotationdummy001()) &&
           VerifyOffset(verifier, VT_CURVEPOSITIONBALL) &&
           verifier.VerifyTable(curvepositionball()) &&
           VerifyOffset(verifier, VT_CURVEROTATIONBALL) &&
           verifier.VerifyTable(curverotationball()) &&
           VerifyOffset(verifier, VT_CURVEPOSITIONBALLPOINTFINGERR) &&
           verifier.VerifyTable(curvepositionballpointfingerr()) &&
           VerifyOffset(verifier, VT_CURVEPOSITIONBALLPOINTFINGERL) &&
           verifier.VerifyTable(curvepositionballpointfingerl()) &&
           VerifyOffset(verifier, VT_CURVEPOSITIONBALLPOINTR) &&
           verifier.VerifyTable(curvepositionballpointr()) &&
           VerifyOffset(verifier, VT_CURVEPOSITIONBALLPOINTL) &&
           verifier.VerifyTable(curvepositionballpointl()) &&
           VerifyOffset(verifier, VT_CURVEROTATIONBALLPOINTR) &&
           verifier.VerifyTable(curverotationballpointr()) &&
           VerifyOffset(verifier, VT_CURVEROTATIONBALLPOINTL) &&
           verifier.VerifyTable(curverotationballpointl()) &&
           VerifyOffset(verifier, VT_EVENTLIST) &&
           verifier.VerifyVector(eventlist()) &&
           verifier.VerifyVectorOfTables(eventlist()) &&
           VerifyField<float>(verifier, VT_LENGTH) &&
           verifier.EndTable();
  }
};

struct TBAnimationInformationBuilder {
  typedef TBAnimationInformation Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(TBAnimationInformation::VT_NAME, name);
  }
  void add_curvepositiondummy001(flatbuffers::Offset<TB::TBVector3Curve> curvepositiondummy001) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEPOSITIONDUMMY001, curvepositiondummy001);
  }
  void add_curverotationdummy001(flatbuffers::Offset<TB::TBQuaternionCurve> curverotationdummy001) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEROTATIONDUMMY001, curverotationdummy001);
  }
  void add_curvepositionball(flatbuffers::Offset<TB::TBVector3Curve> curvepositionball) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEPOSITIONBALL, curvepositionball);
  }
  void add_curverotationball(flatbuffers::Offset<TB::TBQuaternionCurve> curverotationball) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEROTATIONBALL, curverotationball);
  }
  void add_curvepositionballpointfingerr(flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointfingerr) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEPOSITIONBALLPOINTFINGERR, curvepositionballpointfingerr);
  }
  void add_curvepositionballpointfingerl(flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointfingerl) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEPOSITIONBALLPOINTFINGERL, curvepositionballpointfingerl);
  }
  void add_curvepositionballpointr(flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointr) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEPOSITIONBALLPOINTR, curvepositionballpointr);
  }
  void add_curvepositionballpointl(flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointl) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEPOSITIONBALLPOINTL, curvepositionballpointl);
  }
  void add_curverotationballpointr(flatbuffers::Offset<TB::TBQuaternionCurve> curverotationballpointr) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEROTATIONBALLPOINTR, curverotationballpointr);
  }
  void add_curverotationballpointl(flatbuffers::Offset<TB::TBQuaternionCurve> curverotationballpointl) {
    fbb_.AddOffset(TBAnimationInformation::VT_CURVEROTATIONBALLPOINTL, curverotationballpointl);
  }
  void add_eventlist(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TB::TBAnimEvent>>> eventlist) {
    fbb_.AddOffset(TBAnimationInformation::VT_EVENTLIST, eventlist);
  }
  void add_length(float length) {
    fbb_.AddElement<float>(TBAnimationInformation::VT_LENGTH, length, 0.0f);
  }
  explicit TBAnimationInformationBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TBAnimationInformation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TBAnimationInformation>(end);
    return o;
  }
};

inline flatbuffers::Offset<TBAnimationInformation> CreateTBAnimationInformation(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositiondummy001 = 0,
    flatbuffers::Offset<TB::TBQuaternionCurve> curverotationdummy001 = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionball = 0,
    flatbuffers::Offset<TB::TBQuaternionCurve> curverotationball = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointfingerr = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointfingerl = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointr = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointl = 0,
    flatbuffers::Offset<TB::TBQuaternionCurve> curverotationballpointr = 0,
    flatbuffers::Offset<TB::TBQuaternionCurve> curverotationballpointl = 0,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TB::TBAnimEvent>>> eventlist = 0,
    float length = 0.0f) {
  TBAnimationInformationBuilder builder_(_fbb);
  builder_.add_length(length);
  builder_.add_eventlist(eventlist);
  builder_.add_curverotationballpointl(curverotationballpointl);
  builder_.add_curverotationballpointr(curverotationballpointr);
  builder_.add_curvepositionballpointl(curvepositionballpointl);
  builder_.add_curvepositionballpointr(curvepositionballpointr);
  builder_.add_curvepositionballpointfingerl(curvepositionballpointfingerl);
  builder_.add_curvepositionballpointfingerr(curvepositionballpointfingerr);
  builder_.add_curverotationball(curverotationball);
  builder_.add_curvepositionball(curvepositionball);
  builder_.add_curverotationdummy001(curverotationdummy001);
  builder_.add_curvepositiondummy001(curvepositiondummy001);
  builder_.add_name(name);
  return builder_.Finish();
}

inline flatbuffers::Offset<TBAnimationInformation> CreateTBAnimationInformationDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositiondummy001 = 0,
    flatbuffers::Offset<TB::TBQuaternionCurve> curverotationdummy001 = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionball = 0,
    flatbuffers::Offset<TB::TBQuaternionCurve> curverotationball = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointfingerr = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointfingerl = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointr = 0,
    flatbuffers::Offset<TB::TBVector3Curve> curvepositionballpointl = 0,
    flatbuffers::Offset<TB::TBQuaternionCurve> curverotationballpointr = 0,
    flatbuffers::Offset<TB::TBQuaternionCurve> curverotationballpointl = 0,
    const std::vector<flatbuffers::Offset<TB::TBAnimEvent>> *eventlist = nullptr,
    float length = 0.0f) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto eventlist__ = eventlist ? _fbb.CreateVector<flatbuffers::Offset<TB::TBAnimEvent>>(*eventlist) : 0;
  return TB::CreateTBAnimationInformation(
      _fbb,
      name__,
      curvepositiondummy001,
      curverotationdummy001,
      curvepositionball,
      curverotationball,
      curvepositionballpointfingerr,
      curvepositionballpointfingerl,
      curvepositionballpointr,
      curvepositionballpointl,
      curverotationballpointr,
      curverotationballpointl,
      eventlist__,
      length);
}

struct TBAnimationInformationList FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef TBAnimationInformationListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATAS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<TB::TBAnimationInformation>> *datas() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<TB::TBAnimationInformation>> *>(VT_DATAS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATAS) &&
           verifier.VerifyVector(datas()) &&
           verifier.VerifyVectorOfTables(datas()) &&
           verifier.EndTable();
  }
};

struct TBAnimationInformationListBuilder {
  typedef TBAnimationInformationList Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_datas(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TB::TBAnimationInformation>>> datas) {
    fbb_.AddOffset(TBAnimationInformationList::VT_DATAS, datas);
  }
  explicit TBAnimationInformationListBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<TBAnimationInformationList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<TBAnimationInformationList>(end);
    return o;
  }
};

inline flatbuffers::Offset<TBAnimationInformationList> CreateTBAnimationInformationList(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TB::TBAnimationInformation>>> datas = 0) {
  TBAnimationInformationListBuilder builder_(_fbb);
  builder_.add_datas(datas);
  return builder_.Finish();
}

inline flatbuffers::Offset<TBAnimationInformationList> CreateTBAnimationInformationListDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<TB::TBAnimationInformation>> *datas = nullptr) {
  auto datas__ = datas ? _fbb.CreateVector<flatbuffers::Offset<TB::TBAnimationInformation>>(*datas) : 0;
  return TB::CreateTBAnimationInformationList(
      _fbb,
      datas__);
}

struct F4Balance FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef F4BalanceBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KEY = 4,
    VT_VALUE = 6
  };
  const flatbuffers::String *key() const {
    return GetPointer<const flatbuffers::String *>(VT_KEY);
  }
  float value() const {
    return GetField<float>(VT_VALUE, 0.0f);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_KEY) &&
           verifier.VerifyString(key()) &&
           VerifyField<float>(verifier, VT_VALUE) &&
           verifier.EndTable();
  }
};

struct F4BalanceBuilder {
  typedef F4Balance Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_key(flatbuffers::Offset<flatbuffers::String> key) {
    fbb_.AddOffset(F4Balance::VT_KEY, key);
  }
  void add_value(float value) {
    fbb_.AddElement<float>(F4Balance::VT_VALUE, value, 0.0f);
  }
  explicit F4BalanceBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<F4Balance> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<F4Balance>(end);
    return o;
  }
};

inline flatbuffers::Offset<F4Balance> CreateF4Balance(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::String> key = 0,
    float value = 0.0f) {
  F4BalanceBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_key(key);
  return builder_.Finish();
}

inline flatbuffers::Offset<F4Balance> CreateF4BalanceDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const char *key = nullptr,
    float value = 0.0f) {
  auto key__ = key ? _fbb.CreateString(key) : 0;
  return TB::CreateF4Balance(
      _fbb,
      key__,
      value);
}

struct F4BalanceTable FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef F4BalanceTableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATAS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<TB::F4Balance>> *datas() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<TB::F4Balance>> *>(VT_DATAS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATAS) &&
           verifier.VerifyVector(datas()) &&
           verifier.VerifyVectorOfTables(datas()) &&
           verifier.EndTable();
  }
};

struct F4BalanceTableBuilder {
  typedef F4BalanceTable Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_datas(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TB::F4Balance>>> datas) {
    fbb_.AddOffset(F4BalanceTable::VT_DATAS, datas);
  }
  explicit F4BalanceTableBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<F4BalanceTable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<F4BalanceTable>(end);
    return o;
  }
};

inline flatbuffers::Offset<F4BalanceTable> CreateF4BalanceTable(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TB::F4Balance>>> datas = 0) {
  F4BalanceTableBuilder builder_(_fbb);
  builder_.add_datas(datas);
  return builder_.Finish();
}

inline flatbuffers::Offset<F4BalanceTable> CreateF4BalanceTableDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<TB::F4Balance>> *datas = nullptr) {
  auto datas__ = datas ? _fbb.CreateVector<flatbuffers::Offset<TB::F4Balance>>(*datas) : 0;
  return TB::CreateF4BalanceTable(
      _fbb,
      datas__);
}

struct F4SolutionTargetData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef F4SolutionTargetDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTACTPOINT = 4,
    VT_TARGETPOSITION = 6,
    VT_TARGETVELOCITY = 8,
    VT_TARGETREACHTIME = 10,
    VT_ELAPSEDGOALINTIME = 12,
    VT_ELAPSEDREBOUNDABLETIME = 14,
    VT_EVENTNAME = 16
  };
  const TB::Vector3Data *contactpoint() const {
    return GetStruct<const TB::Vector3Data *>(VT_CONTACTPOINT);
  }
  const TB::Vector3Data *targetposition() const {
    return GetStruct<const TB::Vector3Data *>(VT_TARGETPOSITION);
  }
  const TB::Vector3Data *targetvelocity() const {
    return GetStruct<const TB::Vector3Data *>(VT_TARGETVELOCITY);
  }
  float targetreachtime() const {
    return GetField<float>(VT_TARGETREACHTIME, 0.0f);
  }
  float elapsedgoalintime() const {
    return GetField<float>(VT_ELAPSEDGOALINTIME, 0.0f);
  }
  float elapsedreboundabletime() const {
    return GetField<float>(VT_ELAPSEDREBOUNDABLETIME, 0.0f);
  }
  const flatbuffers::String *eventname() const {
    return GetPointer<const flatbuffers::String *>(VT_EVENTNAME);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<TB::Vector3Data>(verifier, VT_CONTACTPOINT) &&
           VerifyField<TB::Vector3Data>(verifier, VT_TARGETPOSITION) &&
           VerifyField<TB::Vector3Data>(verifier, VT_TARGETVELOCITY) &&
           VerifyField<float>(verifier, VT_TARGETREACHTIME) &&
           VerifyField<float>(verifier, VT_ELAPSEDGOALINTIME) &&
           VerifyField<float>(verifier, VT_ELAPSEDREBOUNDABLETIME) &&
           VerifyOffset(verifier, VT_EVENTNAME) &&
           verifier.VerifyString(eventname()) &&
           verifier.EndTable();
  }
};

struct F4SolutionTargetDataBuilder {
  typedef F4SolutionTargetData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_contactpoint(const TB::Vector3Data *contactpoint) {
    fbb_.AddStruct(F4SolutionTargetData::VT_CONTACTPOINT, contactpoint);
  }
  void add_targetposition(const TB::Vector3Data *targetposition) {
    fbb_.AddStruct(F4SolutionTargetData::VT_TARGETPOSITION, targetposition);
  }
  void add_targetvelocity(const TB::Vector3Data *targetvelocity) {
    fbb_.AddStruct(F4SolutionTargetData::VT_TARGETVELOCITY, targetvelocity);
  }
  void add_targetreachtime(float targetreachtime) {
    fbb_.AddElement<float>(F4SolutionTargetData::VT_TARGETREACHTIME, targetreachtime, 0.0f);
  }
  void add_elapsedgoalintime(float elapsedgoalintime) {
    fbb_.AddElement<float>(F4SolutionTargetData::VT_ELAPSEDGOALINTIME, elapsedgoalintime, 0.0f);
  }
  void add_elapsedreboundabletime(float elapsedreboundabletime) {
    fbb_.AddElement<float>(F4SolutionTargetData::VT_ELAPSEDREBOUNDABLETIME, elapsedreboundabletime, 0.0f);
  }
  void add_eventname(flatbuffers::Offset<flatbuffers::String> eventname) {
    fbb_.AddOffset(F4SolutionTargetData::VT_EVENTNAME, eventname);
  }
  explicit F4SolutionTargetDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<F4SolutionTargetData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<F4SolutionTargetData>(end);
    return o;
  }
};

inline flatbuffers::Offset<F4SolutionTargetData> CreateF4SolutionTargetData(
    flatbuffers::FlatBufferBuilder &_fbb,
    const TB::Vector3Data *contactpoint = 0,
    const TB::Vector3Data *targetposition = 0,
    const TB::Vector3Data *targetvelocity = 0,
    float targetreachtime = 0.0f,
    float elapsedgoalintime = 0.0f,
    float elapsedreboundabletime = 0.0f,
    flatbuffers::Offset<flatbuffers::String> eventname = 0) {
  F4SolutionTargetDataBuilder builder_(_fbb);
  builder_.add_eventname(eventname);
  builder_.add_elapsedreboundabletime(elapsedreboundabletime);
  builder_.add_elapsedgoalintime(elapsedgoalintime);
  builder_.add_targetreachtime(targetreachtime);
  builder_.add_targetvelocity(targetvelocity);
  builder_.add_targetposition(targetposition);
  builder_.add_contactpoint(contactpoint);
  return builder_.Finish();
}

inline flatbuffers::Offset<F4SolutionTargetData> CreateF4SolutionTargetDataDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const TB::Vector3Data *contactpoint = 0,
    const TB::Vector3Data *targetposition = 0,
    const TB::Vector3Data *targetvelocity = 0,
    float targetreachtime = 0.0f,
    float elapsedgoalintime = 0.0f,
    float elapsedreboundabletime = 0.0f,
    const char *eventname = nullptr) {
  auto eventname__ = eventname ? _fbb.CreateString(eventname) : 0;
  return TB::CreateF4SolutionTargetData(
      _fbb,
      contactpoint,
      targetposition,
      targetvelocity,
      targetreachtime,
      elapsedgoalintime,
      elapsedreboundabletime,
      eventname__);
}

struct F4SolutionSaveData FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef F4SolutionSaveDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_THROWTYPE = 4,
    VT_SECTORNUM = 6,
    VT_BOUNDTYPE = 8,
    VT_INDEX = 10,
    VT_TARGETDATA = 12
  };
  F4PACKET::SHOT_THROW throwtype() const {
    return static_cast<F4PACKET::SHOT_THROW>(GetField<int8_t>(VT_THROWTYPE, 0));
  }
  int32_t sectornum() const {
    return GetField<int32_t>(VT_SECTORNUM, 0);
  }
  F4PACKET::SHOT_BOUND boundtype() const {
    return static_cast<F4PACKET::SHOT_BOUND>(GetField<int8_t>(VT_BOUNDTYPE, 0));
  }
  int32_t index() const {
    return GetField<int32_t>(VT_INDEX, 0);
  }
  const TB::F4SolutionTargetData *targetdata() const {
    return GetPointer<const TB::F4SolutionTargetData *>(VT_TARGETDATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_THROWTYPE) &&
           VerifyField<int32_t>(verifier, VT_SECTORNUM) &&
           VerifyField<int8_t>(verifier, VT_BOUNDTYPE) &&
           VerifyField<int32_t>(verifier, VT_INDEX) &&
           VerifyOffset(verifier, VT_TARGETDATA) &&
           verifier.VerifyTable(targetdata()) &&
           verifier.EndTable();
  }
};

struct F4SolutionSaveDataBuilder {
  typedef F4SolutionSaveData Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_throwtype(F4PACKET::SHOT_THROW throwtype) {
    fbb_.AddElement<int8_t>(F4SolutionSaveData::VT_THROWTYPE, static_cast<int8_t>(throwtype), 0);
  }
  void add_sectornum(int32_t sectornum) {
    fbb_.AddElement<int32_t>(F4SolutionSaveData::VT_SECTORNUM, sectornum, 0);
  }
  void add_boundtype(F4PACKET::SHOT_BOUND boundtype) {
    fbb_.AddElement<int8_t>(F4SolutionSaveData::VT_BOUNDTYPE, static_cast<int8_t>(boundtype), 0);
  }
  void add_index(int32_t index) {
    fbb_.AddElement<int32_t>(F4SolutionSaveData::VT_INDEX, index, 0);
  }
  void add_targetdata(flatbuffers::Offset<TB::F4SolutionTargetData> targetdata) {
    fbb_.AddOffset(F4SolutionSaveData::VT_TARGETDATA, targetdata);
  }
  explicit F4SolutionSaveDataBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<F4SolutionSaveData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<F4SolutionSaveData>(end);
    return o;
  }
};

inline flatbuffers::Offset<F4SolutionSaveData> CreateF4SolutionSaveData(
    flatbuffers::FlatBufferBuilder &_fbb,
    F4PACKET::SHOT_THROW throwtype = F4PACKET::SHOT_THROW::low,
    int32_t sectornum = 0,
    F4PACKET::SHOT_BOUND boundtype = F4PACKET::SHOT_BOUND::success_clean,
    int32_t index = 0,
    flatbuffers::Offset<TB::F4SolutionTargetData> targetdata = 0) {
  F4SolutionSaveDataBuilder builder_(_fbb);
  builder_.add_targetdata(targetdata);
  builder_.add_index(index);
  builder_.add_sectornum(sectornum);
  builder_.add_boundtype(boundtype);
  builder_.add_throwtype(throwtype);
  return builder_.Finish();
}

struct F4SolutionSaveDataList FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef F4SolutionSaveDataListBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATAS = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<TB::F4SolutionSaveData>> *datas() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<TB::F4SolutionSaveData>> *>(VT_DATAS);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATAS) &&
           verifier.VerifyVector(datas()) &&
           verifier.VerifyVectorOfTables(datas()) &&
           verifier.EndTable();
  }
};

struct F4SolutionSaveDataListBuilder {
  typedef F4SolutionSaveDataList Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_datas(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TB::F4SolutionSaveData>>> datas) {
    fbb_.AddOffset(F4SolutionSaveDataList::VT_DATAS, datas);
  }
  explicit F4SolutionSaveDataListBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<F4SolutionSaveDataList> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<F4SolutionSaveDataList>(end);
    return o;
  }
};

inline flatbuffers::Offset<F4SolutionSaveDataList> CreateF4SolutionSaveDataList(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TB::F4SolutionSaveData>>> datas = 0) {
  F4SolutionSaveDataListBuilder builder_(_fbb);
  builder_.add_datas(datas);
  return builder_.Finish();
}

inline flatbuffers::Offset<F4SolutionSaveDataList> CreateF4SolutionSaveDataListDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<TB::F4SolutionSaveData>> *datas = nullptr) {
  auto datas__ = datas ? _fbb.CreateVector<flatbuffers::Offset<TB::F4SolutionSaveData>>(*datas) : 0;
  return TB::CreateF4SolutionSaveDataList(
      _fbb,
      datas__);
}

}  // namespace TB

#endif  // FLATBUFFERS_GENERATED_ANIMATIONINFORMATION_TB_H_
